{% set name = "wtf-peewee" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: faa953fe3f705d4f2b48f3c1a81c5c5a6a38f9ed1378c9a830e6efc1b0fccb15

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - peewee >=3.0.0
    - wtforms

test:
  imports:
    - wtfpeewee
    - wtfpeewee.fields
    - wtfpeewee.orm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/coleifer/wtf-peewee/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: WTForms integration for peewee models

extra:
  recipe-maintainers:
    - jan-janssen
