{% set name = "wtf-peewee" %}
{% set version = "3.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wtf-peewee-{{ version }}.tar.gz
  sha256: 2d06ce5a0eb9acf4d22d154ae6fbea99db11b1768381c619e78a2ac60a561915

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - peewee >=3.0.0
    - wtforms

test:
  imports:
    - wtfpeewee
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/coleifer/wtf-peewee/
  summary: WTForms integration for peewee models
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
