{% set name = "wtf-peewee" %}
{% set version = "3.0.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "acd05d136c8595da3327fcf9176fa85fdcec1f2aac51d235e46e6fc7a0871283" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - peewee >=3.0.0
    - wtforms

test:
  imports:
    - wtfpeewee
    - wtfpeewee.fields
    - wtfpeewee.orm

about:
  home: https://github.com/coleifer/wtf-peewee/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'WTForms integration for peewee models'

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
