{% set name = "wtf-peewee" %}
{% set version = "3.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7136d845dbc051363ce8c3d1df7047fa703a1ff7a947cb201c380e050fd35244

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - peewee >=3.0.0
    - wtforms

test:
  imports:
    - wtfpeewee
    - wtfpeewee.fields
    - wtfpeewee.orm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/coleifer/wtf-peewee/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: WTForms integration for peewee models

extra:
  recipe-maintainers:
    - jan-janssen
