{% set name = "wtf-peewee" %}
{% set version = "3.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wtf-peewee-{{ version }}.tar.gz
  sha256: 8196446a6e3ab64f1227fba5a8ab31be81775f73d819f75fcafecfd5c0c00b92

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - peewee >=3.0.0
    - wtforms

test:
  imports:
    - wtfpeewee
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/coleifer/wtf-peewee/
  summary: WTForms integration for peewee models
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
